name: skneats_order_portal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_ui_auth: ^1.15.0
  bloc: ^8.1.4
  provider: ^6.1.2
  logger: ^2.4.0
  go_router: ^14.2.8
  firebase_storage: ^12.3.1
  firebase_core: ^3.5.0
  flutter_bloc: ^8.1.6
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
